[2024-09-03T14:50:25.394+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T14:50:25.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T14:50:25.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:49:20.042457+00:00 [queued]>
[2024-09-03T14:50:25.436+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-03T14:50:25.454+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_KPI_theo_nam> on 2024-09-03 09:49:20.042457+00:00
[2024-09-03T14:50:25.468+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=19193) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T14:50:25.471+0000] {standard_task_runner.py:64} INFO - Started process 19201 to run task
[2024-09-03T14:50:25.469+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_KPI_theo_nam', 'manual__2024-09-03T09:49:20.042457+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpp6r2l4vk']
[2024-09-03T14:50:25.474+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask import_csv_KPI_theo_nam
[2024-09-03T14:50:25.497+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T14:50:25.530+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:49:20.042457+00:00 [running]> on host 7932644bd5dc
[2024-09-03T14:50:25.948+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_KPI_theo_nam' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:49:20.042457+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:49:20.042457+00:00'
[2024-09-03T14:50:25.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T14:50:25.971+0000] {logging_mixin.py:188} INFO - Error inserting data into table KPI_theo_nam: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-03T14:50:25.971+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T14:50:25.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T14:50:25.979+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_KPI_theo_nam, run_id=manual__2024-09-03T09:49:20.042457+00:00, execution_date=20240903T094920, start_date=20240903T145025, end_date=20240903T145025
[2024-09-03T14:50:26.049+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-03T14:50:26.067+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T14:50:26.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
