[2024-09-03T15:04:19.020+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T15:04:19.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Du_lieu_ban_hang manual__2024-09-03T09:37:38.383526+00:00 [queued]>
[2024-09-03T15:04:19.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Du_lieu_ban_hang manual__2024-09-03T09:37:38.383526+00:00 [queued]>
[2024-09-03T15:04:19.061+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-03T15:04:19.077+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Du_lieu_ban_hang> on 2024-09-03 09:37:38.383526+00:00
[2024-09-03T15:04:19.090+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T15:04:19.089+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Du_lieu_ban_hang', 'manual__2024-09-03T09:37:38.383526+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpnfvdjn61']
[2024-09-03T15:04:19.091+0000] {standard_task_runner.py:64} INFO - Started process 20188 to run task
[2024-09-03T15:04:19.092+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask import_csv_Du_lieu_ban_hang
[2024-09-03T15:04:19.108+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T15:04:19.142+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Du_lieu_ban_hang manual__2024-09-03T09:37:38.383526+00:00 [running]> on host 7932644bd5dc
[2024-09-03T15:04:19.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Du_lieu_ban_hang' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:37:38.383526+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:37:38.383526+00:00'
[2024-09-03T15:04:19.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T15:04:19.545+0000] {logging_mixin.py:188} INFO - Error inserting data into table Du_lieu_ban_hang: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-03T15:04:19.546+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T15:04:19.547+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T15:04:19.552+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_Du_lieu_ban_hang, run_id=manual__2024-09-03T09:37:38.383526+00:00, execution_date=20240903T093738, start_date=20240903T150419, end_date=20240903T150419
[2024-09-03T15:04:19.586+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-03T15:04:19.601+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T15:04:19.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
