[2024-09-03T15:04:23.694+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T15:04:23.734+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien manual__2024-09-03T09:36:40.134056+00:00 [queued]>
[2024-09-03T15:04:23.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien manual__2024-09-03T09:36:40.134056+00:00 [queued]>
[2024-09-03T15:04:23.745+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-03T15:04:23.765+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_Nhan_vien> on 2024-09-03 09:36:40.134056+00:00
[2024-09-03T15:04:23.775+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20199) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T15:04:23.776+0000] {standard_task_runner.py:64} INFO - Started process 20213 to run task
[2024-09-03T15:04:23.775+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_Nhan_vien', 'manual__2024-09-03T09:36:40.134056+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpr1ampfrm']
[2024-09-03T15:04:23.777+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask import_csv_Nhan_vien
[2024-09-03T15:04:23.793+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T15:04:23.825+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_Nhan_vien manual__2024-09-03T09:36:40.134056+00:00 [running]> on host 7932644bd5dc
[2024-09-03T15:04:24.219+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_Nhan_vien' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:36:40.134056+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:36:40.134056+00:00'
[2024-09-03T15:04:24.221+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T15:04:24.247+0000] {logging_mixin.py:188} INFO - Error inserting data into table Nhan_vien: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-03T15:04:24.248+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T15:04:24.249+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T15:04:24.260+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_Nhan_vien, run_id=manual__2024-09-03T09:36:40.134056+00:00, execution_date=20240903T093640, start_date=20240903T150423, end_date=20240903T150424
[2024-09-03T15:04:24.312+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-03T15:04:24.332+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T15:04:24.333+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
