[2024-09-03T15:04:23.707+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-03T15:04:23.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:36:40.134056+00:00 [queued]>
[2024-09-03T15:04:23.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:36:40.134056+00:00 [queued]>
[2024-09-03T15:04:23.755+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-03T15:04:23.785+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): import_csv_KPI_theo_nam> on 2024-09-03 09:36:40.134056+00:00
[2024-09-03T15:04:23.797+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-03T15:04:23.799+0000] {standard_task_runner.py:64} INFO - Started process 20217 to run task
[2024-09-03T15:04:23.800+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'import_csv_to_mysql', 'import_csv_KPI_theo_nam', 'manual__2024-09-03T09:36:40.134056+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/import_csv_to_mysql_dag.py', '--cfg-path', '/tmp/tmpl3erk509']
[2024-09-03T15:04:23.802+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask import_csv_KPI_theo_nam
[2024-09-03T15:04:23.818+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-03T15:04:23.846+0000] {task_command.py:426} INFO - Running <TaskInstance: import_csv_to_mysql.import_csv_KPI_theo_nam manual__2024-09-03T09:36:40.134056+00:00 [running]> on host 7932644bd5dc
[2024-09-03T15:04:24.261+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congdat' AIRFLOW_CTX_DAG_ID='import_csv_to_mysql' AIRFLOW_CTX_TASK_ID='import_csv_KPI_theo_nam' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T09:36:40.134056+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T09:36:40.134056+00:00'
[2024-09-03T15:04:24.263+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-03T15:04:24.288+0000] {logging_mixin.py:188} INFO - Error inserting data into table KPI_theo_nam: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-03T15:04:24.289+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-03T15:04:24.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-03T15:04:24.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=import_csv_to_mysql, task_id=import_csv_KPI_theo_nam, run_id=manual__2024-09-03T09:36:40.134056+00:00, execution_date=20240903T093640, start_date=20240903T150423, end_date=20240903T150424
[2024-09-03T15:04:24.375+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-03T15:04:24.384+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
